# Star Parameters for Abell3571 in the b (1) filter
MIN_MAG: 27
MAX_MAG: 21
MIN_SIZE: 2
MAX_SIZE: 3.5
MIN_SNR: 20

# Path/name to truth file (NOT ACCURATE NAMING OR PATH YET)
truthfilepath: '/Users/j.mccleary/Research/SuperBIT/real_data/Abell3571/b/coadd/Abell3571_b_star_cat.fits'
