# Star Parameters for Abell3571 in the b (1) filter
MIN_MAG: 22.6
MAX_MAG: 16
MIN_SIZE: 1.1
MAX_SIZE: 3.0
MIN_SNR: 20

# Path/name to truth file (NOT ACCURATE NAMING OR PATH YET)
truthfilepath: /home/wslgeorgios/bit/oba_temp/Abell3571/b/Abell3571_b_truth.fits